### ISSUE TITLE
Sticky header covers scroll targets

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#401]
**Describe the bug**

When a notebook contains edits, Observable sticks the notebook menu bar to to the top of the viewport.

This bar covers jump targets (anchors, search results) and thus several impedes navigation and orientation within a notebook.

**Expected behavior**

Scrolling to elements is offset by the height of the sticky bar.

**Additional context**

This is an longstanding problem that has likely been touched on in other issues as well.

**Comment by mootari** [comment]
**Workaround**

Add a user style sheet with the following content:
```css
@-moz-document url-prefix("https://observablehq.com/") {
  #__next .node-focus .ͼ5 {
    background-color: var(--near-white);
  }
  #__next div[data-node-id], .cm-content > div {
    scroll-margin-top: 52px;
    scroll-margin-bottom: 52px;
  }
}
```
This also fixes the scrolling issues described in https://github.com/observablehq/feedback/issues/291#issuecomment-1079665613.
