### ISSUE TITLE
Give Fork's a unique title initially" (Fork of) ___

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#453]
I use forks to atomically merge changes into a prod notebook. However, in about 70% of the time I get confused which is the original and which is the fork, sometimes with disastrous results. Here is my activity chart of a typical "Patch a prod notebook"

<img width="758" alt="image" src="https://user-images.githubusercontent.com/1848162/175532851-e200d9c9-3393-4be7-931b-47714c36026f.png">

Could you tell which ones were the fork and which were prod?

It's confusing in a few other places beyond the activity feed, like the browser tab. Forks could be given a name like "(Fork of) Login with comment" until the title is explicitly updated. Note I deliberately but the parenthesis first so the browser tab would be distinguishable.

This would be like the OS behaviour when you copy a file, it appends (Copy of)

**Comment by mootari** [comment]
For what it's worth, as a workaround you could add a user style like
```css
@-moz-document url("https://observablehq.com/") {
  .listing-grid + div + div.relative > a[href^="/d/"] {
     position: relative;
  }
  .listing-grid + div + div.relative > a[href^="/d/"]:after {
    content: attr(href);
    position: absolute;
    bottom: 2px;
    font: 500 var(--font-size-7) var(--sans-serif);
    color: var(--gray);
    left: calc(16px + 24px + var(--spacing-small));
    width: auto;
  }
}
```
which would give you
<img width="757" alt="image" src="https://user-images.githubusercontent.com/322014/175539265-3ce2130e-4fd6-44d9-8771-1c5faa990671.png">
